#!/usr/bin/env bash
#
# Install or update this repository's skills for opencode by cloning/updating
# the repo, linking each skill into ~/.config/opencode/skills, and adding the
# local skill directories to ~/.config/opencode/opencode.json for newer opencode
# releases. Also creates or refreshes matching slash commands in
# ~/.config/opencode/commands, overlaying any hand-written opencode command
# templates from this repo.

set -euo pipefail

REPO_URL="${MY_SKILLS_REPO_URL:-https://github.com/kterto/my-skills.git}"
INSTALL_DIR="${MY_SKILLS_INSTALL_DIR:-$HOME/.config/opencode/my-skills}"
CONFIG_FILE="${OPENCODE_CONFIG_FILE:-$HOME/.config/opencode/opencode.json}"
GLOBAL_SKILLS_DIR="${OPENCODE_SKILLS_DIR:-$HOME/.config/opencode/skills}"
GLOBAL_COMMANDS_DIR="${OPENCODE_COMMANDS_DIR:-$HOME/.config/opencode/commands}"
SHARED_SKILLS_PATH="$INSTALL_DIR/plugins/my-skills/skills"
OPENCODE_SKILLS_PATH="$INSTALL_DIR/.opencode/skills"
OPENCODE_COMMANDS_PATH="$INSTALL_DIR/.opencode/commands"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required command not found: $1" >&2
    exit 1
  fi
}

require_cmd git
require_cmd node

mkdir -p "$(dirname "$INSTALL_DIR")" "$(dirname "$CONFIG_FILE")" "$GLOBAL_SKILLS_DIR" "$GLOBAL_COMMANDS_DIR"

if [ -d "$INSTALL_DIR/.git" ]; then
  echo "Updating $INSTALL_DIR"
  git -C "$INSTALL_DIR" pull --ff-only
elif [ -e "$INSTALL_DIR" ]; then
  echo "error: $INSTALL_DIR exists but is not a git checkout" >&2
  echo "Move it aside or set MY_SKILLS_INSTALL_DIR to a different path." >&2
  exit 1
else
  echo "Cloning $REPO_URL -> $INSTALL_DIR"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi

if [ ! -d "$SHARED_SKILLS_PATH" ]; then
  echo "error: expected skills directory not found: $SHARED_SKILLS_PATH" >&2
  exit 1
fi

ts="$(date +%Y%m%d-%H%M%S)"
for skills_dir in "$SHARED_SKILLS_PATH" "$OPENCODE_SKILLS_PATH"; do
  [ -d "$skills_dir" ] || continue

  for skill in "$skills_dir"/*/; do
    name="$(basename "$skill")"
    target="$GLOBAL_SKILLS_DIR/$name"

    if [ -L "$target" ]; then
      rm "$target"
    elif [ -e "$target" ]; then
      mv "$target" "$target.bak-$ts"
      echo "backed up existing opencode skill $name -> $name.bak-$ts"
    fi

    ln -s "${skill%/}" "$target"
    echo "linked opencode skill $name -> ${skill%/}"
  done
done

SKILLS_PATHS="$SHARED_SKILLS_PATH"
if [ -d "$OPENCODE_SKILLS_PATH" ]; then
  SKILLS_PATHS="$SKILLS_PATHS:$OPENCODE_SKILLS_PATH"
fi

export SKILLS_PATHS GLOBAL_COMMANDS_DIR OPENCODE_COMMANDS_PATH
node <<'NODE'
const fs = require("fs")
const path = require("path")

const skillsPaths = process.env.SKILLS_PATHS.split(path.delimiter).filter(Boolean)
const commandsDir = process.env.GLOBAL_COMMANDS_DIR
const commandTemplatesDir = process.env.OPENCODE_COMMANDS_PATH
const timestamp = new Date().toISOString().replace(/[-:]/g, "").replace(/\..+/, "")
const marker = "<!-- Generated by kterto/my-skills install-opencode.sh. Safe to replace. -->"

function extractFrontmatter(markdown) {
  const match = markdown.match(/^---\n([\s\S]*?)\n---/)
  if (!match) return {}

  const data = {}
  for (const line of match[1].split("\n")) {
    const field = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/)
    if (!field) continue
    data[field[1]] = field[2].trim().replace(/^["']|["']$/g, "")
  }
  return data
}

function yamlString(value) {
  return JSON.stringify(value.replace(/\s+/g, " ").trim())
}

function writeManagedCommand(commandFile, content, label) {
  if (fs.existsSync(commandFile)) {
    const existing = fs.readFileSync(commandFile, "utf8")
    if (!existing.includes(marker)) {
      fs.renameSync(commandFile, `${commandFile}.bak-${timestamp}`)
      console.log(`backed up existing opencode command ${path.basename(commandFile)} -> ${path.basename(commandFile)}.bak-${timestamp}`)
    }
  }

  fs.writeFileSync(commandFile, content)
  console.log(label)
}

for (const skillsPath of skillsPaths) {
  for (const name of fs.readdirSync(skillsPath).sort()) {
    const skillDir = path.join(skillsPath, name)
    const skillFile = path.join(skillDir, "SKILL.md")
    if (!fs.statSync(skillDir, { throwIfNoEntry: false })?.isDirectory()) continue
    if (!fs.statSync(skillFile, { throwIfNoEntry: false })?.isFile()) continue

    const frontmatter = extractFrontmatter(fs.readFileSync(skillFile, "utf8"))
    const commandFile = path.join(commandsDir, `${name}.md`)
    const description = frontmatter.description || `Run the ${name} skill`
    const command = `---\ndescription: ${yamlString(description)}\n---\n${marker}\n\nUse the skill tool to load the \`${name}\` skill, then execute it with these arguments exactly as provided:\n\n\`\`\`text\n$ARGUMENTS\n\`\`\`\n\nDo not answer from memory before loading the skill. If the arguments are empty, follow the skill's default invocation behavior.\n`

    writeManagedCommand(commandFile, command, `installed opencode command /${name}`)
  }
}

if (fs.statSync(commandTemplatesDir, { throwIfNoEntry: false })?.isDirectory()) {
  for (const fileName of fs.readdirSync(commandTemplatesDir).sort()) {
    if (!fileName.endsWith(".md")) continue
    const sourceFile = path.join(commandTemplatesDir, fileName)
    if (!fs.statSync(sourceFile, { throwIfNoEntry: false })?.isFile()) continue

    const destinationFile = path.join(commandsDir, fileName)
    const source = fs.readFileSync(sourceFile, "utf8")
    const content = source.replace(/^(---\n[\s\S]*?\n---\n?)/, `$1\n${marker}\n`)
    writeManagedCommand(destinationFile, content, `installed opencode command template /${path.basename(fileName, ".md")}`)
  }
}
NODE

export CONFIG_FILE SKILLS_PATHS
node <<'NODE'
const fs = require("fs")
const path = require("path")

const configFile = process.env.CONFIG_FILE
const skillsPaths = process.env.SKILLS_PATHS.split(path.delimiter).filter(Boolean)
const timestamp = new Date().toISOString().replace(/[-:]/g, "").replace(/\..+/, "")

let config = {}
if (fs.existsSync(configFile)) {
  const raw = fs.readFileSync(configFile, "utf8").trim()
  if (raw) {
    try {
      config = JSON.parse(raw)
    } catch (error) {
      console.error(`error: ${configFile} must be valid JSON for this installer to edit it safely.`)
      console.error("If you use JSONC comments/trailing commas, add the skills.paths entry manually from the README.")
      process.exit(1)
    }
  }
  fs.copyFileSync(configFile, `${configFile}.bak-${timestamp}`)
}

config.$schema ??= "https://opencode.ai/config.json"
config.skills ??= {}
config.skills.paths ??= []

if (!Array.isArray(config.skills.paths)) {
  console.error(`error: ${configFile} has skills.paths, but it is not an array.`)
  process.exit(1)
}

for (const skillsPath of skillsPaths) {
  if (!config.skills.paths.includes(skillsPath)) {
    config.skills.paths.push(skillsPath)
  }
}

fs.mkdirSync(path.dirname(configFile), { recursive: true })
fs.writeFileSync(configFile, `${JSON.stringify(config, null, 2)}\n`)
NODE

echo
echo "opencode skills paths installed:"
for skills_dir in "$SHARED_SKILLS_PATH" "$OPENCODE_SKILLS_PATH"; do
  [ -d "$skills_dir" ] && echo "  $skills_dir"
done
echo "opencode global skill links installed in: $GLOBAL_SKILLS_DIR"
echo "opencode slash commands installed in: $GLOBAL_COMMANDS_DIR"
echo "Config updated: $CONFIG_FILE"
echo "Run this installer again to update skills and command templates."
echo "Restart opencode to load the skills."
